services:
  server:
    build: .
    image: fsrsync
    container_name: server
    hostname: server
    environment:
      - OPERATION=${OPERATION}
      - ENVFILE="/app/config/test.json"
    volumes:
      - ./config:/app/config/
      - ./test/source:/root/source
    expose:
      - 8080:8080
    networks:
      - shared-net

  client:
    build: .
    image: fsrsync
    container_name: client
    hostname: client
    environment:
      - OPERATION=${OPERATION}
    volumes:
      - ./config:/app/config/
      - ./test/destination:/root/destination
    expose:
      - 8081:8081
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge