services:
  client:
    build: .
    image: fsrsync
    container_name: client
    hostname: client
    environment:
      - OPERATION=${OPERATION}
    volumes:
      - ./test/destination:/root/destination
    networks:
      - shared-net

  server:
    build: .
    image: fsrsync
    container_name: server
    hostname: server
    environment:
      - OPERATION=${OPERATION}
    volumes:
      - ./config/test.json:/etc/fsrsync/config.json
      - ./test/source:/root/source
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge