WAIT_5_SEC = 5  # 5 seconds
WAIT_30_SEC = 30  # 30 seconds
WAIT_60_SEC = 60  # 1 minute
WAIT_1H = 3600  # 1 hour
WAIT_2H = 7200  # 2 hours
ZERO = 0  # Zero
DEFAULT_MAX_STATS = 10  # Default number of stats to keep
EXCLUDE_ALL = ['*']  # Exclude all files
EXCLUDE_NONE = []  # Empty list
DEFAULT_FULL_SYNC = 60  # 1 minute
CHECK_THREADS_SLEEP = 300  # 5 minutes
DEFAULT_HTTP_TIMEOUT = 120  # 2 minutes
